
bin/CS_HEADERS.o:       src/CS_HEADERS.cpp
        g++ -O -s -m64   -c   -o bin/CS_HEADERS.o src/CS_HEADERS.cpp -I hdr  -std=gnu++0x
bin/SIPENGINE.o:        src/SIPENGINE.cpp
        g++ -O -s -m64   -c   -o bin/SIPENGINE.o src/SIPENGINE.cpp -I hdr  -std=gnu++0x
bin/TRNSPRT.o:  src/TRNSPRT.cpp
        g++ -O -s -m64   -c   -o bin/TRNSPRT.o src/TRNSPRT.cpp -I hdr  -std=gnu++0x
bin/ACTION.o:   src/ACTION.cpp
        g++ -O -s -m64   -c   -o bin/ACTION.o src/ACTION.cpp -I hdr  -std=gnu++0x
bin/TRNSCT_SM.o:        src/TRNSCT_SM.cpp
        g++ -O -s -m64   -c   -o bin/TRNSCT_SM.o src/TRNSCT_SM.cpp -I hdr  -std=gnu++0x
bin/DAO.o:      src/DAO.cpp
        g++ -O -s -m64   -c   -o bin/DAO.o src/DAO.cpp -I hdr  -std=gnu++0x
bin/SL_CC.o:    src/SL_CC.cpp
        g++ -O -s -m64   -c   -o bin/SL_CC.o src/SL_CC.cpp -I hdr  -std=gnu++0x
bin/COMAP.o:    src/COMAP.cpp
        g++ -O -s -m64   -c   -o bin/COMAP.o src/COMAP.cpp -I hdr  -std=gnu++0x
bin/ALARM.o:    src/ALARM.cpp
        g++ -O -s -m64   -c   -o bin/ALARM.o src/ALARM.cpp -I hdr  -std=gnu++0x
bin/ALO.o:      src/ALO.cpp
        g++ -O -s -m64   -c   -o bin/ALO.o src/ALO.cpp -I hdr  -std=gnu++0x
bin/SUDP.o:     src/SUDP.cpp
        g++ -O -s -m64   -c   -o bin/SUDP.o src/SUDP.cpp -I hdr  -std=gnu++0x
